### ISSUE TITLE
demoapp crashes on attachment selection.

### ISSUE THREAD

**Issue by chetanshingala** [customerly/Customerly-Android-SDK#5]
I am facing issue with setAttachmentsAvailable. I have set Customerly.setAttachmentsAvailable(true) still it is not allowing me to select attachment file. so do we need any extra configuration for this? or what ever the configuration we have in demoapp it is ok ?  So is it issue? or it is not part of free version or something that way it is crashing? I am able to hide attachment  option if I set Customerly.setAttachmentsAvailable(false). 

Please note that while selecting attachment option it is asking for permission and I have given all permissions. but it is still crashing.

Here is the logcat log: [logcat.txt](https://github.com/Customerly/Android-SDK/files/8217608/logcat.txt)

ERROR:

```
    --------- beginning of crash
2022-03-10 01:01:51.142 19355-19355/io.customerly.demoapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.customerly.demoapp, PID: 19355
    kotlin.UninitializedPropertyAccessException: lateinit property attachmentFileChooserLauncher has not been initialized
        at io.customerly.activity.ClyIInputActivity.access$getAttachmentFileChooserLauncher$p(ClyIInputActivity.kt:64)
        at io.customerly.activity.ClyIInputActivity$attachButtonListener$1.invoke(ClyIInputActivity.kt:102)
        at io.customerly.activity.ClyIInputActivity$attachButtonListener$1.invoke(ClyIInputActivity.kt:64)
        at io.customerly.activity.ClyIInputActivityKt$sam$i$android_view_View_OnClickListener$0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2022-03-10 01:01:51.144 1892-2003/? W/ActivityManager:   Force finishing activity io.customerly.demoapp/io.customerly.activity.chat.ClyChatActivity
2022-03-10 01:01:51.145 1624-4484/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 9478252 , only wrote 9478080
2022-03-10 01:01:51.365 19355-19355/io.customerly.demoapp I/Process: Sending signal. PID: 19355 SIG: 9
```

Thanks.

**Comment by michael-timi** [comment]
this issue still persists, any solution on it?
